package net.yumix.simplemail;

import jakarta.mail.MessagingException;

public class UncheckedMessagingException extends RuntimeException {

    /**
     * Serial Version (Generated by Eclipse)
     */
    private static final long serialVersionUID = 6737830928831337416L;

    public UncheckedMessagingException(MessagingException cause) {
        super(cause);
    }

    public UncheckedMessagingException(String message, MessagingException cause) {
        super(message, cause);
    }

}
